# ==============================================================
# ????????? ??????????? ? ???? ??????
# ==============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vet_clinic_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:RBPO1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# ????????? JPA
# ==============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ????????? ????????????? ?????????, ???? ?????? schema.sql/data.sql ???
spring.sql.init.mode=never

# ==============================================================
# ????????? JWT
# ==============================================================
app.jwt.secret=${JWT_SECRET:MySecretKeyForJwtAuthenticationVetClinicApplication2024}
app.jwt.access-expiration=${JWT_ACCESS_EXP:900000}
app.jwt.refresh-expiration=${JWT_REFRESH_EXP:604800000}

# ==============================================================
# ????????? HTTPS (SSL)
# ==============================================================
server.port=8443
server.ssl.enabled=true
# ???????, ??? ???? studentServer.jks ????? ? src/main/resources/
server.ssl.key-store=classpath:studentServer.jks
server.ssl.key-store-type=JKS
server.ssl.key-store-password=${SSL_STORE_PASSWORD:serverPass23271}
server.ssl.key-alias=server_23271

# ????????? ???????????? ???????? ?????? ? ?????
logging.level.org.springframework.security=INFO